### ISSUE TITLE
ORA field summary_documentation and SE field 'Abstract' for certain work types (e.g. Ephemera)

### ISSUE THREAD

**Issue by mrdsaunders** [tomwrobel/ora_data_model#138]
For a patent the METS via Sword show:
`<mods:abstract type="summary_documentation">abstract test patent</mods:abstract>`

`uuid_e587ddee-50d6-40f0-89d3-f709cb6ebf0e `

However this field displays on the record as label `abstract` as opposed to `Summary documentation`:
![image](https://user-images.githubusercontent.com/11141619/69636241-0e33f100-104e-11ea-828b-b9b9bf0e0739.png)

Can I confirm that this is expected behaviour?

**Comment by jjpartridge** [comment]
summary_documentation is available for item types of Dataset, Patent, Physical Object and Ephemera. It is instead of the field 'abstract' which we have decided these item types wont have in ORA. In SE I guess the corresponding field is abstract, and it send to ORA's summary documentation based on type of work. As for how it is returned, unless you have (or are creating) a 'summary documentation' field abstract seems the appropriate one.  (@tomwrobel @mrdsaunders )

**Comment by mrdsaunders** [comment]
Ah, me getting confused. We deposit to abstract type="summary_documentation" but harvest back to abstract.

Thanks.

**Comment by tomwrobel** [comment]
@mrdsaunders at present, deposit of ephemera is sending Oxris abstract (ORA summary documentation) as:

```
<mods:abstract>Summary documentation content</mods:abstract>
```

It should be:

```
<mods:abstract type="summary_documentation>Summary documentation content</mods:abstract>
```

**Comment by tomwrobel** [comment]
@mrdsaunders see 1077937 / uuid_8c753c8c-3078-4f1c-aa62-e31df1daea94 for example objects

**Comment by tomwrobel** [comment]
@mrdsaunders what is the status of this ticket? :) sorry for bugging you

**Comment by mrdsaunders** [comment]
It's a bug. Can I ask is it possible (both theoretically in xml and in reality in ORA) for the following data to co-exist for device, ephemera, artefact or patent:

`<mods:abstract>Summary documentation content</mods:abstract>`
`<mods:abstract type="summary_documentation>Summary documentation content2</mods:abstract>`
