### ISSUE TITLE
Manual record in Oxris doesn't match ORA4 source 

### ISSUE THREAD

**Issue by tobypitts** [tomwrobel/ora_data_model#177]
I was presented with this record today 1077331 / uuid_c115e941-f55b-429c-b4a7-b347315e4c81

This is an un-reviewed item. 

At first glance it looks as if the ORA4 source in Oxris is incorrect as it does not match the current manual source in SE, the deposited file or the other sources in SE. 

However, we have a working hypothesis that the manual record may have been changed after deposit and that the ORA source in SE is displaying the details from the original manual record which took priority over the other sources on the SE record, at the time of deposit. 

Could we please confirm that this is indeed what happened with this record?

**Comment by tomwrobel** [comment]
Just to add that:

- The version in ORA4 Symp is being read correctly by Oxris
- The ORA4 object in ORA4 Symp is completely unchanged from initial deposit
- The ORA4 logs show the object was transfered immediately on deposit to ORA4 Review with the journal title as it stands in ORA4
- the record has not been edited in ORA4 Review (it remains as it was transferred there on deposit)

The journal in the ORA4 record contains a paper published in the same month as the Oxris record (June 2019) by the same authors on the same topic.

Given that ORA4 doesn't share information about authors, journal titles, etc. between records, and given that no related items were moving through the system at the time, the possibility of data corruption in ORA is very low. The logical assumption is that the data ORA holds is the data that was originally sent (a manual record with an error in it). 

Unfortunately, because it was sent at the start of the month, we no longer have a copy of the XML request to verify this.

**Comment by tomwrobel** [comment]
@mrdsaunders one for you on your return! Welcome back and sorry :(

**Comment by mrdsaunders** [comment]
A quick question for @tobypitts - would an ORA reviewer ever add in a PubMed identifier?

**Comment by tobypitts** [comment]
@mrdsaunders We wouldn't add one in ORA4 no

**Comment by mrdsaunders** [comment]
So this suggests to me that it was deposited whilst the PubMed record was linked as a source for the object. Since PubMed is higher precedence that manual, that was the data that was sent to ORA.

**Comment by mrdsaunders** [comment]
The history shows that the manual record was amended twice after deposit, but we can't tell what was changed. Either way there is a data discrepancy on that object - we will investigate further to see whether these should be separate outputs.
