### ISSUE TITLE
Deposit to ORA4 failing due to character in filename

### ISSUE THREAD

**Issue by mrdsaunders** [tomwrobel/ora_data_model#183]
https://oxris.ox.ac.uk/viewobject.html?id=1083813&cid=1

The following file is failing deposit to the above object:

[Validation of Plasma Proteomic Biomarkers Relating to Brain Amyloid Burden in the EMIF-Alzheimer’s Disease Multimodal Biomarker Discovery Cohort.pdf](https://github.com/tomwrobel/ora_data_model/files/4539615/Validation.of.Plasma.Proteomic.Biomarkers.Relating.to.Brain.Amyloid.Burden.in.the.EMIF-Alzheimer.s.Disease.Multimodal.Biomarker.Discovery.Cohort.pdf)

Error log:
[deposit error.txt](https://github.com/tomwrobel/ora_data_model/files/4539623/deposit.error.txt)

If I remove the apostrophe character it successfully deposits. I believe the character is `U+2019 : RIGHT SINGLE QUOTATION MARK {single comma quotation mark}`.

Prior to further investigation with S Ltd, is this possibly an ORA4 issue?

**Comment by jjpartridge** [comment]
Hi @mrdsaunders yes could be - we have had other examples of when certain characters are in file names that issues occur, and usually taking out the character or replacing it with standard keys solves the issue. 

I think this is one for FAQs or guidance on file formatting for deposit rather than developer effort if i'm honest.

**Comment by mrdsaunders** [comment]
Hi Jason, I'm not necessarily asking for developer effort here, rather an explanation of why this character is not permissible, so that we understand better. For such a FAQ it would be helpful to tell people what characters can and can't be included i.e. what constitutes a standard character for this purpose, since it seems that some are allowable and others not. I know characterises are a minefield but is there an 'easy' answer to this question based on what we know about Hyrax?

**Comment by jjpartridge** [comment]
Hmm. don't know the answer to that i'm afraid. I think that there were issues in ORA3 with this sort of thing previous too, so it may not be Hyrax specific, but maybe general file-uploader (or possibly Fedora). I would suspect any non-ascii characters should be avoided as a general rule @tomwrobel  any thoughts on this?

General web browsing: 
- https://stackoverflow.com/questions/11721147/invalid-characters-in-a-filename-on-windows
- https://www.mtu.edu/umc/services/digital/writing/characters-avoid/

**Comment by jjpartridge** [comment]
Hmm. don't know the answer to that i'm afraid. I think that there were issues in ORA3 with this sort of thing previous too, so it may not be Hyrax specific, but maybe general file-uploader (or possibly Fedora). I would suspect any non-ascii characters should be avoided as a general rule @tomwrobel  any thoughts on this?

General web browsing: 
- https://stackoverflow.com/questions/11721147/invalid-characters-in-a-filename-on-windows
- https://www.mtu.edu/umc/services/digital/writing/characters-avoid/

**Comment by tomwrobel** [comment]
@mrdsaunders the attached file has a title that makes this VERY difficult to replicate, because downloading the file just creates a 'safe' version of the filename. However, when I do, there is no recorded POST request in the ORA4 Hyrax logs. All I see is a 400 error in the Apache logs. I don't think the error is necessarily at the ORA4 end.

The issue might not be with the filename itself but with the HTTPS headers. The filename is included in the Content-Disposition HTTPS header, and only ASCII characters are allowed in HTTPS header values - non ASCII should be URL escaped (I think, see
https://stackoverflow.com/questions/47687379/what-characters-are-allowed-in-http-header-values)

**Comment by tomwrobel** [comment]
To add, we're not even getting a Sword BagIt package created here. The failure is VERY early in the chain

**Comment by mrdsaunders** [comment]
Thanks Tom. I think then that we can go with the advice 'if in doubt - ASCII only'.
