### ISSUE TITLE
Update an individual Symplectic Elements record from Hyrax on demand

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#66]
IF

- I create or claim a record in SE AND
- Deposit a file in Hyrax/ORA for that record AND
- Update the record in Hyrax/ORA AND
- I want to see the updated Hyrax/ORA metadata in SE

THEN

- I have to do a full re-harvest of the Hyrax Data Source in Repotool 2

This seems a little strange. Is there a way to update a single record's metadata on demand, rather than doing a full re-index?

**Comment by AndrewBennet** [comment]
These changes should be picked up by the Differential Harvest operation, which runs every hour. This is the job which queries the OAI-PMH endpoint for a list of IDs of the items which have changed since it last ran, and enqueues any items it finds into a queue of items to be re-fetched. Is this not working for you? Or did you just want to see the changes quicker than after 1 hour?

There is an undocumented trick for triggering a refresh of an item, which is useful when testing: when on the publications list page ("objects.html"), if you click the Full Text tab for a given publication, that item's repository records will be refetched and updated straight-away

**Comment by tomwrobel** [comment]
I think the hack should work fine! I'll check here.

Is it the case than in RT1 a record automatically updates whenever anyone goes to the publication page (viewobject.html)? Or have I misunderstood?

**Comment by tomwrobel** [comment]
Yup, that's fine! Closing.

**Comment by AndrewBennet** [comment]
> I think the hack should work fine! I'll check here.
> 
> Is it the case than in RT1 a record automatically updates whenever anyone goes to the publication page (viewobject.html)? Or have I misunderstood?

Yes, you're right.
