### ISSUE TITLE
SQL script to inform Symplectic Elements of Hyrax identifiers for existing Publications

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#74]
We're coming into the deployment phase of our Elements <-> Hyrax Repotool 2 Connector development.

The new Repotool 2 connection replaces an existing Repotool 1 connection. There are c. 180,000 Publications record <-> ORA object relationships maintained via Repotool 1. We need to maintain these relationships in Repotool 2

As such, we need to know how to tell Symplectic Elements about existing publications in the new Hyrax machine. 

Our planned deployment:

1) Create new ORA Hyrax machine
2) Connect to SE via Repotool 2 as a metadata source
  2.1) Maintain SE Repotool 1 connection for deposit until migration is complete
3) Migrate ORA3 content into Hyrax machine
4) Ensure existing SE records that were connected to ORA3 content via Repotool 1 maintain that connection under Repotool 2
5) Once migration is complete, and updates are synced to Repotool 2, switch deposit connection to Repotool 2

As I understand it, step 4 is achieved via an SQL script. What is the format of that script, and how do we run/deploy? I can't find any documentation on the support site! 

To close this ticket:

- [ ] The format of that script
- [ ] Instructions for running the script

**Comment by AndrewBennet** [comment]
Hi Tom,

Step 4 is achieved by running a standalone executable on the Elements server: `dbmigraterepositorytools.exe`. This executable is shipped separately by us, upon request. There is a config file alongside the executable which contains a setting `rt2-source-name`, which - in your case - should be set to `hyrax`. 

The executable takes as an input the path to a CSV file containing mappings between Elements integer publication IDs and repository (RT2) item IDs. The CSV file should have headers:

> elements_id, repository_item_id

Running the program will instruct Elements to store an association between the publication and a record from the Hyrax datasource of the given ID. When/if a record of a stored ID eventually gets ingested, Elements will prioritise this stored association rather than use its matching normal matching algorithm, which will result in the record being injected into the relevant Elements publication object.

I'll check whether we have any more-detailed documentation than this; perhaps not, given that RT1-RT2 migrations are usually performed in close communication with us anyway. What's your planned timeline for steps 4 & 5?

Cheers,
Andrew

**Comment by tomwrobel** [comment]
Hi Andrew

Thanks for the very quick reply!

We are planning to action steps 4 and 5 in August (w/c August 5, 2019).

However, we need to test this aspect of the deployment. Our migration testing has shown us that a longer, and slower, migration may be necessary. If it is possible to run the new RT2 Hyrax as a metadata source next to RT1 as a deposit connection, then we'd very much like to do that.

We want to test our deployment, and the possibility of side-by-side running, in two phases:

a) functional testing: to start w/c June 03
b) load testing with a full(ish) set of objects: to start w/c June 24

Ideally, therefore, we'd need the executable ready to deploy for June 03, is this possible?
Is it also possible to run RT1 for deposit and RT2 for Hyrax as a metadata source side by side?

With very best wishes, and blue skies

Tom

**Comment by AndrewBennet** [comment]
Hi Tom,

Sounds good. I can indeed pass you the tool to perform the migration - I will get that to you shortly. In order to do so, could you confirm the exact version of Elements you're running (down to the minor version number)? Can you see this on the Help page in Elements.

It is technically possible to run RT1 and RT2 side-by-side; we would only recommend doing so as a temporary measure. Am I right in understanding that you'd want to run them side-by-side only until the migration is complete? If so, then yes - that's OK.

All the best,
Andrew

**Comment by tomwrobel** [comment]
Hi @AndrewBennet 

You updated this and I didn't see it! Apologies. The version is 5.15.0.2199 release build

Yup, we'll only be doing things temporarily (for a few weeks?). 

With best wishes, and blue skies

Tom
