### ISSUE TITLE
Questions regarding SE field 'version'

### ISSUE THREAD

**Issue by mrdsaunders** [tomwrobel/ora_data_model#87]
From `ORA to SE mapping`:
```
<symplectic_field name="version">
            <if test="describing a record"><ora_field>record_version</ora_field></if>
            <if test="describing a binary file"><ora_field>binary_files__file_version</ora_field></if>
            <if test="describing a binary file's Rioxx/Open access status, e.g. Version of Record"><ora_field>binary_files__file_rioxx_file_version</ora_field></if>
</symplectic_field>
```

The Symplectic field `version` for a `record` is mapped to ORA field `record_version`

In `ORA to mets` this is mapped to the admin data:
```
<mods:extension>
	<ora_admin:admin>
		<ora_admin:record_version>field:record_version</ora_admin:record_version>
```

Q1: In terms of the harvest crosswalk, should it in fact take data from:

```
<ora_dataset:dataset>
	<dc:version>field:data_digital_data_version</dc:version>
```

Q2: SE also uses the field `version` in type `working paper`. Do we wish to amend the mapping/mets/model to account for this (e.g. be explicit it is dataset only and not crosswalk, or crosswalk to somewhere else)?

Q3: What is the distinction between the following (relevant to deposit crosswalk)

```
<mods:extension>
	<ora_admin:admin>
		<ora_admin:record_version>field:record_version</ora_admin:record_version>
```
and

```
<ora:repository_file>
	<dcterms:hasVersion>field:binary_files__file_version</dcterms:hasVersion>
```

**Comment by jjpartridge** [comment]
@mrdsaunders OK. This seems to be a little mixed up. 

'record_version' does not need to be in the Crosswalks, this will not be implemented in the initial release of ORA4 and relates only to the actual versioning of the ORA public record not bibliographic info. 

'data_digital_data_version' is a dataset specific field and therefore only applies to those item types that we categorise as data. This is likely to be an integer rather than "AAM" or "VoR" (for example)

For Crosswalks in (to ORA) SE 'Version' should be passed to 'binary_files__files_version' for the appropriate file. I believe that there is some logic on ORA's side that will then perform mappings (after Review) to populate the field 'binary_files__file_rioxx_file_version'.

On crosswalk out (back to SE) the value from 'binary_files__file_rioxx_file_version' should then be passed to SE field 'Version'.

Hope that makes things clearer

**Comment by mrdsaunders** [comment]
Terminology: with apologies for being SE-centric it might be an idea if we standardise on 'Harvest' or 'In' for ORA->SE and 'Deposit' or 'Out'  for SE->ORA.

Also, distinction between version for a) bibliographic info (as per software version 1.0)  b) versioning of the ORA record and c) file version e.g. RIOXX.

So I suggest
1. SE version field holds bibliographic info so binary_files__file_rioxx_file_version should not map to it as per your reply but to SE repository-items/oa-location-file-version
2. data_digital_data_version for datasets should map to SE field 'version'.
3. SE is configured to also hold a (possibly non-numeric) version for working papers e.g. v2,v3 There is currently no place for this in ORA4 so it will not be crosswalked. 

Cheers

**Comment by tomwrobel** [comment]
FWIW I'm happy with Deposit and Harvest, as they reflect the likely flow of most data in the system

**Comment by mrdsaunders** [comment]
Agreed at ORA-SE 17/10/2019. File version (not RIOXX) is held at both ORA file and object level. 

For datasets SE version maps to data_digital_data_version
otherwise there is no object level mapping to or from this field.

**Comment by mrdsaunders** [comment]
```
<symplectic_field name="version">
    <if test="type = Software/code">
        <ora_field>data_digital_data_version</ora_field><note>At object level</note>
    </if>
    <if test="type = Software/code or Working paper">
    <ora_field>binary_files__file_version</ora_field> <note>At file level, if multiple files then take value from first file</note>
    </if>
</symplectic_field>
```
