### ISSUE TITLE
SE to ORA mapping correction for thesis-type

### ISSUE THREAD

**Issue by mrdsaunders** [tomwrobel/ora_data_model#93]
To update SE to ORA mapping document, please confirm that:
`<symplectic_field name="thesis-type"><ora_field>degree_level</ora_field></symplectic_field>`

should read:

`<symplectic_field name="thesis-type"><ora_field>*thesis_*degree_level</ora_field></symplectic_field>`

**Comment by tomwrobel** [comment]
@mrdsaunders correct. Would you like to change it, or shall I?

**Comment by mrdsaunders** [comment]
So the general question is do ORA  ‘own’ the mapping document or are you happy for me to amend?

**Comment by tomwrobel** [comment]
ORA doesn't own it. I think Oxford vs Symplectic Ltd might be an issue, but otherwise no.

It's all in Git, and it's all traceable (git blame is everyone's friend) and revertable. So long as you aren't merging your own changes, then I'm happy for you to treat is as jointly owned because, well, it is jointly owned.

**Comment by mrdsaunders** [comment]
Thanks Tom, just wasn’t sure of the background.

**Comment by mrdsaunders** [comment]
Pull request #96
